- name: Install required packages
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Run hello-world container
  command: docker run hello-world